name: Tests

on: push

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.2.1
      with:
        version: "5.6"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Tests
      run: swift test
